NumPy is a Python library for creating and manipulating vectors and matrices.

In [61]:
#import numpy
import numpy as np

## Populate arrays with specific numbers

Call `np.array` to create a NumPy matrix with your own hand-picked values. For example, the following call to `np.array` creates an 5-element vector:

In [62]:
oneDArray = np.array([1,2,3,4,5])
print(oneDArray)

[1 2 3 4 5]


In [63]:
##Creating 2D Arrays

twoDArray =  np.array([[1,2],[3,4],[5,6]])
twoDArray,type(twoDArray)

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 numpy.ndarray)

In [64]:
#Creates 1D Array whose each element is a list
twoDArray =  np.array([[1,2],[3],[5,6]])
twoDArray,type(twoDArray),twoDArray[0]

<ipython-input-64-e2f8506b30f2>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  twoDArray =  np.array([[1,2],[3],[5,6]])


(array([list([1, 2]), list([3]), list([5, 6])], dtype=object),
 numpy.ndarray,
 [1, 2])

In [65]:
# a matrix with all zeroes, call np.zeros. 

np.zeros(3), np.zeros((3,3))


(array([0., 0., 0.]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]))

In [66]:
# a matrix with all ones, call np.ones.

np.ones(3), np.ones((3,4))

(array([1., 1., 1.]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]))

## Populate arrays with sequences of numbers


In [67]:
#You can populate an array with a sequence of numbers
seq=np.arange(5,120)
print(seq)

[  5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22
  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40
  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58
  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76
  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94
  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111 112
 113 114 115 116 117 118 119]


In [68]:
#populating an array with alternative numbers
seq=np.arange(5,120,2)
print(seq)

[  5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35  37  39
  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71  73  75
  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107 109 111
 113 115 117 119]


In [69]:
#populating an array with every 5th numbers
seq=np.arange(5,120,5)
print(seq)

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100 105 110 115]


## Array with Random numbers

NumPy provides various functions to populate matrices with random numbers across certain ranges. For example, `np.random.randint` generates random integers between a low and high value. The following call populates a 6-element vector with random integers between 10 and 100. The highest generated integer is one less than the `high` argument.

In [70]:
#np.random.randint(low=10,high=100,size=6)
#default value for size is 1 
randomarray=np.random.randint(10,100,6)
randomarray

array([70, 86, 58, 85, 50, 48])

In [71]:
#To create random floating-point values between 0.0 and 1.0, call `np.random.random`. 

np.random.random(10)

array([0.65682183, 0.55393334, 0.81425738, 0.29214584, 0.41551191,
       0.155913  , 0.9508133 , 0.01190527, 0.0806794 , 0.34972322])

## Mathematical Operations on NumPy Operands


In [72]:
#If you want to add or subtract two vectors or matrices, linear algebra requires that the two operands have the same dimensions.
#Furthermore, if you want to multiply two vectors or matrices, linear algebra imposes strict rules on the dimensional compatibility of operands. 
#Fortunately, NumPy uses a trick called **broadcasting** to virtually expand the smaller operand to dimensions compatible for linear algebra.
#For example, the following operation uses broadcasting to add 6.0 to the value of every item in the vector created.

In [73]:
randomarray=np.random.randint(10,100,6)
randomarray,randomarray+6

(array([50, 41, 95, 60, 35, 33]), array([ 56,  47, 101,  66,  41,  39]))

In [74]:
#The following operation also relies on broadcasting to multiply each cell in a vector by 3:
randomarray=np.random.randint(10,20,6)
randomarray,randomarray*3

(array([12, 11, 18, 17, 13, 11]), array([36, 33, 54, 51, 39, 33]))

In [75]:
noise = np.random.random(3) #creates 3 fp numbers between 0 and 1
print(noise,type(noise))

[0.06327313 0.2134568  0.24331687] <class 'numpy.ndarray'>


In [76]:
noise = np.random.uniform(-2,2,15)  # generates a random floating number between -2 and 2
#noise = (np.random.random([15]) * 4) - 2 
noise

array([ 0.97119073, -1.88164257, -0.28776444,  0.34469766,  0.40990361,
       -1.90391771,  0.58932156, -1.79009069,  0.08770406, -1.69368097,
        0.97674425, -1.33497526, -1.87066121, -1.50967278,  1.88365874])